/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateScanHistoryArgs } from "./CreateScanHistoryArgs";
import { UpdateScanHistoryArgs } from "./UpdateScanHistoryArgs";
import { DeleteScanHistoryArgs } from "./DeleteScanHistoryArgs";
import { ScanHistoryFindManyArgs } from "./ScanHistoryFindManyArgs";
import { ScanHistoryFindUniqueArgs } from "./ScanHistoryFindUniqueArgs";
import { ScanHistory } from "./ScanHistory";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { User } from "../../user/base/User";
import { ScanHistoryService } from "../scanHistory.service";

@graphql.Resolver(() => ScanHistory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ScanHistoryResolverBase {
  constructor(
    protected readonly service: ScanHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "read",
    possession: "any",
  })
  async _scanHistoriesMeta(
    @graphql.Args() args: ScanHistoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ScanHistory])
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "read",
    possession: "any",
  })
  async scanHistories(
    @graphql.Args() args: ScanHistoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ScanHistory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ScanHistory",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ScanHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "read",
    possession: "own",
  })
  async scanHistory(
    @graphql.Args() args: ScanHistoryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ScanHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ScanHistory",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ScanHistory)
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "create",
    possession: "any",
  })
  async createScanHistory(
    @graphql.Args() args: CreateScanHistoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ScanHistory> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ScanHistory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ScanHistory"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        users: {
          connect: args.data.users,
        },
      },
    });
  }

  @graphql.Mutation(() => ScanHistory)
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "update",
    possession: "any",
  })
  async updateScanHistory(
    @graphql.Args() args: UpdateScanHistoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ScanHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ScanHistory",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ScanHistory"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          users: {
            connect: args.data.users,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ScanHistory)
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "delete",
    possession: "any",
  })
  async deleteScanHistory(
    @graphql.Args() args: DeleteScanHistoryArgs
  ): Promise<ScanHistory | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Product])
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "read",
    possession: "any",
  })
  async products(
    @graphql.Parent() parent: ScanHistory,
    @graphql.Args() args: ProductFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Product[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Product",
    });
    const results = await this.service.findProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ScanHistory",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: ScanHistory,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
