version: "3"
services:
  database:
    image: "mongo"
    container_name: "palau-test-container"
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE: AmplicationDB
      - MONGO_INITDB_ROOT_USERNAME: admin
      - MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
      - ./data/mongo-volume:/data/db

